services:
  app:
    depends_on:
      - db
    environment:
      PRETTY_URLS: "1"
      HTTPS: "1"
      HTTPS_REDIRECT: "1"
      LANG: "en-US"
      BASE_URL: "${E_BASE_URL}"
      DB_TYPE: "mysql"
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_USER: "webtrees"
      DB_PASS: "${E_DB_PASS}"
      DB_NAME: "webtrees"
      DB_PREFIX: "wt_"
      WT_USER: "${E_WT_USER}"
      WT_NAME: "${E_WT_USER}"
      WT_PASS: "${E_WT_PASS}"
      WT_EMAIL: "${E_WT_EMAIL}"
      PUID: "1000"
      PGID: "1000"
    image: ghcr.io/nathanvaughn/webtrees:latest
    ports:
      - 443:443
    restart: unless-stopped
    volumes:
      - app_certs:/certs/
      - app_data:/var/www/webtrees/data/
      - app_themes:/var/www/webtrees/modules_v4/
      - ./bin/generate_cert.sh:/generate_cert.sh
    entrypoint: ["/bin/bash", "-c", "/generate_cert.sh && exec python3 /docker-entrypoint.py"]

  db:
    environment:
      MARIADB_DATABASE: "webtrees"
      MARIADB_USER: "webtrees"
      MARIADB_ROOT_PASSWORD: "${E_MARIADB_ROOT_PASSWORD}"
      MARIADB_PASSWORD: "${E_MARIADB_PASSWORD}"
    # See: https://github.com/NathanVaughn/webtrees-docker/issues/145
    image: docker.io/library/mariadb:latest
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql

  # db:
  #   environment:
  #     POSTGRES_DB: "webtrees"
  #     POSTGRES_USER: "webtrees"
  #     POSTGRES_PASSWORD: "badpassword"
  #   image: docker.io/library/postgres:latest
  #   restart: unless-stopped
  #   volumes:
  #     - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
  app_data:
    driver: local
  app_certs:
    driver: local
  app_themes:
    driver: local
